---
- name: disable swap (if configured).
  command: swapoff -a
  tags: ['skip_ansible_lint']

- name: ensure swap file doesn't exist (if configured).
  ansible.builtin.file:
    path: "{{ swap_file_path }}"
    state: absent

- name: Disable swappiness.
  ansible.posix.sysctl:
    name: vm.swappiness
    value: 0
    state: present
