---

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: update apt cache.
  ansible.builtin.apt: update_cache=true cache_valid_time=600
  when: ansible_os_family == 'Debian'

- name: manage swap file entry in fstab.
  ansible.posix.mount:
    name: none
    src: "{{ swap_file_path }}"
    fstype: swap
    opts: sw
    state: "{{ swap_file_state }}"

- include_tasks: disable.yml
  when: swap_file_state == 'absent'

- include_tasks: enable.yml
  when: swap_file_state == 'present'
